### ISSUE TITLE
Buildable when?

### ISSUE THREAD

**Issue by Lqnz** [ssllllll/RusherHack-b10-src#2]
lol

**Comment by ssllllll** [comment]
When i get rhack properties to build, i alredy tried to build but i made the src's publics so the people can skid it

**Comment by notperry1234567890** [comment]
> lol

bro its so easy do it urself skid

**Comment by Notme11** [comment]
@notperry1234567890 pls make rusherhack skid

**Comment by notperry1234567890** [comment]
> @notperry1234567890 pls make rusherhack skid

who r u
